name: fkn_labs
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  card_swiper: ^2.0.1
  dio: ^4.0.6
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Marvel
      fonts:
        - asset: fonts/Marvel/Marvel-Regular.ttf
        - asset: fonts/Marvel/Marvel-Italic.ttf
          style: italic
        - asset: fonts/Marvel/Marvel-Bold.ttf
          weight: 700